# Generated by Django 4.1 on 2022-08-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbscrapping',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
