# Generated by Django 4.1 on 2022-08-05 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapping', '0002_imdbscrapping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbscrapping',
            name='amount',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='categories',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='runtime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='vote',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='year',
            field=models.TextField(),
        ),
    ]
