# Generated by Django 4.1 on 2022-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapping', '0003_alter_imdbscrapping_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbscrapping',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='categories',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='rating',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='runtime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='vote',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='imdbscrapping',
            name='year',
            field=models.CharField(max_length=200),
        ),
    ]
